# Generated by Django 6.0.1 on 2026-07-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_student_profile_picture_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
