# Generated by Django 6.0.1 on 2026-07-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_student_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
